### ISSUE TITLE
CW2Q6 RVIZ issue

### ISSUE THREAD

**Issue by MOYF-beta** [surgical-vision/MPHY0054_lab#1]
when the rviz was launched by cw2q6py.launch, warning occurs constantly:
![image](https://github.com/user-attachments/assets/22d55959-3dca-4ea4-9530-00ddb90e7a91)
in rviz, there are also some errors:
![image](https://github.com/user-attachments/assets/8f5e7e82-2fb7-478b-bd51-6fc8417dea07)

**Comment by MOYF-beta** [comment]
also i used plt to draw the scatters, it seems ok. i guess the rviz issue is not my bug because those warning occurs before i launch my python node
![image](https://github.com/user-attachments/assets/bb25346b-920f-4615-a778-0ea0cdb62d96)

**Comment by MOYF-beta** [comment]
here is my q6() function:
```python
    def q6(self):
        """ This is the main q6 function. Here, other methods are called to create the shortest path required for this
        question. Below, a general step-by-step is given as to how to solve the problem.
        Returns:
            traj (JointTrajectory): A list of JointTrajectory points giving the robot joint positions to achieve in a
            given time period.
        """
        # Steps to solving Q6.
        # 1. Load in targets from the bagfile (checkpoint data and target joint positions).
        # 2. Compute the shortest path achievable visiting each checkpoint Cartesian position.
        # 3. Determine intermediate checkpoints to achieve a linear path between each checkpoint and have a full list of
        #    checkpoints the robot must achieve. You can publish them to see if they look correct. Look at slides 39 in lecture 7
        # 4. Convert all the checkpoints into joint values using an inverse kinematics solver.
        # 5. Create a JointTrajectory message.

        # Your code starts here ------------------------------
        ... (as this is a public issue, code omitted but should be correct)
        self.publish_traj_tfs(full_checkpoint_tfs)
        # Your code ends here ------------------------------

        assert isinstance(traj, JointTrajectory)
        print("Trajectory created")
        return traj
```

and here is the code i used to create the plot, only adding some code in the end:
```python
    def publish_traj_tfs(self, tfs):
        """This function gets a np.ndarray of transforms and publishes them in a color coded fashion to show how the
        Cartesian path of the robot end-effector.
        Args:
            tfs (np.ndarray): A array of 4x4xn homogenous transformations specifying the end-effector trajectory.
        """
        id = 0
        for i in range(0, tfs.shape[2]):
            marker = Marker()
            marker.id = id
            id += 1
            marker.header.frame_id = 'base_link'
            marker.header.stamp = rospy.Time.now()
            marker.type = marker.SPHERE
            marker.action = marker.ADD
            marker.scale.x = 0.01
            marker.scale.y = 0.01
            marker.scale.z = 0.01
            marker.color.a = 1.0
            marker.color.r = 0.0
            marker.color.g = 0.0 + id * 0.05
            marker.color.b = 1.0 - id * 0.05
            marker.pose.orientation.w = 1.0
            marker.pose.position.x = tfs[0, -1, i]
            marker.pose.position.y = tfs[1, -1, i]
            marker.pose.position.z = tfs[2, -1, i]
            self.checkpoint_pub.publish(marker)
            # Visualize the checkpoints using matplotlib, since rviz have bugs with the markers
            import matplotlib.pyplot as plt
            fig = plt.figure()
            ax = fig.add_subplot(111, projection='3d')
            ax.scatter(tfs[0, -1, :], tfs[1, -1, :], tfs[2, -1, :], c='r', marker='o')
            ax.set_xlabel('X Label')
            ax.set_ylabel('Y Label')
            ax.set_zlabel('Z Label')
            plt.show()
```

**Comment by MOYF-beta** [comment]
now there is another issue, this error occur before cw2q6 code actually runs.
```
[INFO] [1733789079.279249, 114.228000]: Waiting 5 seconds for everything to load up.
[ERROR] [1733789079.280736, 114.229000]: bad callback: <bound method YoubotKinematicBase.joint_state_callback of <cw2q4.youbotKineKDL.YoubotKinematicKDL object at 0x7fb8e0679940>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/mnt/c/Users/14152/Desktop/course/MPHY0054/CW2/src/cw2q4/src/cw2q4/youbotKineBase.py", line 50, in joint_state_callback
    current_pose = self.forward_kinematics(self.current_joint_position)
  File "/mnt/c/Users/14152/Desktop/course/MPHY0054/CW2/src/cw2q4/src/cw2q4/youbotKineKDL.py", line 63, in forward_kinematics
    self.fk_solver.JntToCart(joints_kdl, pose_kdl)
AttributeError: 'YoubotKinematicKDL' object has no attribute 'fk_solver'

Trajectory created
```

**Comment by MOYF-beta** [comment]
i fixed this by remove '/' in line 120 in youbot_rviz_cw2/src/main.cpp
```cpp
points.header.frame_id = robot_trail.header.frame_id = reached_points.header.frame_id = "base_link";
```
